name: Vue project Ingeration

on:
    push:
        branches:
            - main


jobs:
    project-building:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v4

            - name: Build Image
              run: |
                IMAGE_NAME=vue-with-nginx >> $GITHUB_ENV

                SAFE_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/-/g')

                if [ "${{ github.event_name }}" == "push" ]; then
                
                    TAG=${SAFE_BRANCH}-$(date +%Y%m%d%H%M%S) >> $GITHUB_ENV

                elif [ "${{ github.event_name }}" == "pull_request" ]; then
                    
                TAG=pr-${{ github.event.pull_request.number }}-${{ github.sha_short }} >> $GITHUB_ENV

                else
                    # Fallback: Use short SHA
                    TAG=${{ github.sha_short }} >> $GITHUB_ENV
                fi

                echo "Testing image name................"
                echo $IMAGE_NAME:$TAG
                echo "Testing image name................"
                docker build -t mahabub01/$IMAGE_NAME:$TAG .
                docker tag mahabub01/$IMAGE_NAME:$TAG mahabub01/$IMAGE_NAME:latest



            - name: Push Image
              run: | 
                echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u mahabub01 --password-stdin
                echo "Testing name .............................."
                echo "mahabub01/"
                echo $IMAGE_NAME:$TAG
                echo "Testing name .............................."
                docker push mahabub01/$IMAGE_NAME:$TAG
                docker push mahabub01/$IMAGE_NAME:latest
                
