name: Vue project Ingeration

on:
    push:
        branches:
            - main


jobs:
    project-building:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v4

            - name: Build Image
              run: docker build -t mahabub01/vue-with-nginx:latest .

            - name: Push Image
              run: | 
                docker login -u mahabub01 -p ${{ secrets.DOCKERHUB_PASSWORD }}
                docker push mahabub01/vue-with-nginx:latest
