name: Vue project Ingeration

on:
    push:
        branches:
            - main


jobs:
    project-building:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v4

            - name: Build Image
              run: |
                IMAGE_NAME=vue-with-nginx

                if [ "${{ github.event_name }}" == "push" ]; then
                    TAG=$(echo ${{ github.ref_name }} | sed 's/\//-/g')-$(date +%Y%m%d%H%M%S)
                else
                    TAG=pr-${{ github.event.pull_request.number }}
                fi

                docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG .
                docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest



            - name: Push Image
              run: | 
                docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
                
