name: Vue Project Integration

on:
  push:
    branches:
      - main

jobs:
  project-building:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |

          # Build the Docker image
          docker build -t mahabub01/${{ github.repository}}:${{ github.ref_name}} .
          docker tag mahabub01/vue-with-nginx:${{ github.ref_name}} mahabub01/vue-with-nginx:latest

      - name: Push Docker Image
        run: |

          # Log in to Docker Hub
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          # Push the image to Docker Hub
          docker push mahabub01/${{ github.repository}}:${{ github.ref_name}}
          docker push mahabub01/${{ github.repository}}:latest